### ISSUE TITLE
Enlive mangles Stencil/Mustache templates

### ISSUE THREAD

**Issue by RadicalZephyr** [AdamFrey/boot-asset-fingerprint#1]
Hey, so I use Mustache templates that I want to process with `asset-fingerprint`, but Enlive turns all `<` and `>` into `&lt;` or `&gt;` respectively...  Thus the mustache partial syntax is destroyed:

``` mustache
{{> awesome/partial }}
```
becomes:

``` mustache
{{&gt; awesome/partial }}
```

This doesn't work so well.

What I'm wondering about is why use Enlive at all?  For large HTML files it's slow, and seems like a lot of really unnecessary work.  I forked this task, and prototyped just using `clojure.string/replace` and a simple regex and it seems to work just fine.  I was wondering if you have a good reason for using Enlive in the first place, and whether you would be open to a PR that adds some features (being able to specify a host where assets should be fetched from) and also either:
- replaces the Enlive processing with the string replace
- OR adds string processing as a task option

**Comment by AdamFrey** [comment]
Does your forked version still use the `${...}` syntax for asset references or does it use something else?

I would definitely be open to your PR, I'm not married to Enlive.
